cam::strategy
bool cam::strategy.SHAPELY
cam.strategy.cutout(o)
References cam.strategy.checkminz, cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.curve(o)
References cam.strategy.checkminz, cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.proj_curve(s, o)
References cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.pocket(o)
References cam.strategy.checkminz, cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.drill(o)
References cam.strategy.checkminz, cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.medial_axis(o)
References cam.strategy.chunksToMesh, cam.strategy.getLayers.
cam.strategy.getLayers(operation, startdepth, enddepth)
Returns a List of Layers Bounded by Startdepth and Enddepth Uses Operation.stepdown to Determine Number of Layers.
Referenced by cam.strategy.curve, cam.strategy.cutout, cam.strategy.drill, cam.strategy.medial_axis, cam.strategy.pocket, cam.strategy.proj_curve.
cam.strategy.chunksToMesh(chunks, o)
Convert Sampled Chunks to Path, Optimization of Paths
Referenced by cam.strategy.curve, cam.strategy.cutout, cam.strategy.drill, cam.strategy.medial_axis, cam.strategy.pocket, cam.strategy.proj_curve.
cam.strategy.checkminz(o)
Referenced by cam.strategy.curve, cam.strategy.cutout, cam.strategy.drill, cam.strategy.pocket.