cam::involute_gear
cam.involute_gear.gear_polar(r, theta)
Referenced by cam.involute_gear.gear, cam.involute_gear.gear_q6.
cam.involute_gear.gear_iang(r1, r2)
Referenced by cam.involute_gear.gear, cam.involute_gear.gear_q6.
cam.involute_gear.gear_q7(f, r, b, r2, t, s)
References cam.involute_gear.gear_q6.
Referenced by cam.involute_gear.gear.
cam.involute_gear.gear_q6(b, s, t, d)
References cam.involute_gear.gear_iang, cam.involute_gear.gear_polar.
Referenced by cam.involute_gear.gear_q7.
cam.involute_gear.gear(mm_per_tooth=0.003, number_of_teeth=5, hole_diameter=0.003175, pressure_angle=0.3488, clearance=0.0, backlash=0.0, rim_size=0.0005, hub_diameter=0.006, spokes=4)
References cam.involute_gear.gear_iang, cam.involute_gear.gear_polar, cam.involute_gear.gear_q7.
cam.involute_gear.rack(mm_per_tooth=0.01, number_of_teeth=11, height=0.012, pressure_angle=0.3488, backlash=0.0, hole_diameter=0.003175, tooth_per_hole=4)