cam::utils
bool cam::utils.SHAPELY
bool cam::utils.USE_PROFILER
dict cam::utils.was_hidden_dict
bool cam::utils._IS_LOADING_DEFAULTS
cam::utils.changed
cam::utils.update_offsetimage_tag
cam::utils.update_zbufferimage_tag
cam.utils.opencamlib_version()
cam.utils.positionObject(operation)
cam.utils.getBoundsWorldspace(obs, use_modifiers=False)
cam.utils.getSplineBounds(ob, curve)
cam.utils.getOperationSources(o)
cam.utils.getBounds(o)
cam.utils.getBoundsMultiple(operations)
Gets Bounds of Multiple Operations, Mainly for Purpose of Simulations or Rest Milling. Highly Suboptimal.
cam.utils.samplePathLow(o, ch1, ch2, dosample)
Referenced by cam.utils.connectChunksLow.
cam.utils.sampleChunks(o, pathSamples, layers)
cam.utils.sampleChunksNAxis(o, pathSamples, layers)
cam.utils.extendChunks5axis(chunks, o)
cam.utils.curveToShapely(cob, use_modifiers=False)
Referenced by cam.utils.getAmbient, cam.utils.polygonBoolean, cam.utils.silhoueteOffset.
cam.utils.silhoueteOffset(context, offset, style=1, mitrelimit=1.0)
References cam.utils.curveToShapely.
cam.utils.polygonBoolean(context, boolean_type)
References cam.utils.curveToShapely.
cam.utils.polygonConvexHull(context)
cam.utils.Helix(r, np, zstart, pend, rev)
cam.utils.comparezlevel(x)
cam.utils.overlaps(bb1, bb2)
cam.utils.connectChunksLow(chunks, o)
Connects Chunks that Are Close to Each Other without Lifting, Sampling Them 'low'
References cam.utils.samplePathLow.
cam.utils.getClosest(o, pos, chunks)
Referenced by cam.utils.sortChunks.
cam.utils.sortChunks(chunks, o, last_pos=None)
References cam.utils.getClosest.
cam.utils.getVectorRight(lastv, verts)
cam.utils.cleanUpDict(ndict)
References cam.utils.dictRemove.
cam.utils.dictRemove(dict, val)
Referenced by cam.utils.cleanUpDict.
cam.utils.addLoop(parentloop, start, end)
References cam.utils.addLoop.
Referenced by cam.utils.addLoop.
cam.utils.cutloops(csource, parentloop, loops)
References cam.utils.cutloops.
Referenced by cam.utils.cutloops.
cam.utils.getOperationSilhouete(operation)
Gets Silhouette for the Operation Uses Image Thresholding for Everything Except Curves.
cam.utils.getObjectSilhouete(stype, objects=None, use_modifiers=False)
cam.utils.getAmbient(o)
References cam.utils.curveToShapely.
cam.utils.getObjectOutline(radius, o, Offset)
cam.utils.addOrientationObject(o)
The Orientation Object Should Be Used to Set up Orientations of the Object for 4 and 5 Axis Milling.
Referenced by cam.utils.updateStrategy.
cam.utils.removeOrientationObject(o)
Referenced by cam.utils.updateStrategy.
cam.utils.addTranspMat(ob, mname, color, alpha)
cam.utils.addMachineAreaObject()
cam.utils.addMaterialAreaObject()
Referenced by cam.utils.update_material, cam.utils.updateMaterial.
cam.utils.getContainer()
cam.utils.unique(L)
Return a List of Unhashable Elements in S, but without Duplicates. [[1, 2], [2, 3], [1, 2]] >>> [[1, 2], [2, 3]]
cam.utils.checkEqual(lst)
cam.utils.prepareIndexed(o)
References cam.utils.rotTo2axes.
cam.utils.cleanupIndexed(operation)
cam.utils.rotTo2axes(e, axescombination)
Converts an Orientation Object Rotation to Rotation Defined by 2 Rotational Axes on the Machine - for Indexed Machining. Attempting to Do This for All Axes Combinations.
Referenced by cam.utils.prepareIndexed.
cam.utils.reload_paths(o)
cam.utils.updateMachine(self, context)
cam.utils.updateMaterial(self, context)
References cam.utils.addMaterialAreaObject.
cam.utils.updateOperation(self, context)
cam.utils.isValid(o, context)
cam.utils.operationValid(self, context)
cam.utils.isChainValid(chain, context)
cam.utils.updateOperationValid(self, context)
cam.utils.updateChipload(self, context)
This Is Very Simple Computation of Chip Size, Could Be Very Much Improved
cam.utils.updateOffsetImage(self, context)
Refresh Offset Image Tag for Rerendering
cam.utils.updateZbufferImage(self, context)
Changes Tags so Offset and Zbuffer Images Get Updated on Calculation Time.
cam.utils.updateStrategy(o, context)
References cam.utils.addOrientationObject, cam.utils.removeOrientationObject, cam.utils.updateExact.
cam.utils.updateCutout(o, context)
cam.utils.updateExact(o, context)
Referenced by cam.utils.update_exact_mode, cam.utils.updateStrategy.
cam.utils.updateOpencamlib(o, context)
Referenced by cam.utils.update_opencamlib.
cam.utils.updateBridges(o, context)
cam.utils.updateRotation(o, context)
cam.utils.updateRest(o, context)
cam.utils.getStrategyList(scene, context)
cam.utils.update_material(self, context)
References cam.utils.addMaterialAreaObject.
cam.utils.update_operation(self, context)
cam.utils.update_exact_mode(self, context)
References cam.utils.updateExact.
cam.utils.update_opencamlib(self, context)
References cam.utils.updateOpencamlib.
cam.utils.update_zbuffer_image(self, context)
cam.utils.check_operations_on_load(context)
Checks Any Broken Computations on Load and Reset Them.
cam.utils.Add_Pocket(self, maxdepth, sname, new_cutter_diameter)