cam::basrelief
float cam::basrelief.EPS
int cam::basrelief.PRECISION
bool cam::basrelief.NUMPYALG
cam.basrelief.copy_compbuf_data(inbuf, outbuf)
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.restrictbuf(inbuf, outbuf)
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.prolongate(inbuf, outbuf)
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.idx(r, c, cols)
cam.basrelief.smooth(U, F, linbcgiterations, planar)
References cam.basrelief.linbcg.
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.calculate_defect(D, U, F)
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.add_correction(U, C)
Referenced by cam.basrelief.solve_pde_multigrid.
cam.basrelief.solve_pde_multigrid(F, U, vcycleiterations, linbcgiterations, smoothiterations, mins, levels, useplanar, planar)
References cam.basrelief.add_correction, cam.basrelief.calculate_defect, cam.basrelief.copy_compbuf_data, cam.basrelief.prolongate, cam.basrelief.restrictbuf, cam.basrelief.smooth.
Referenced by cam.basrelief.relief.
cam.basrelief.asolve(b, x)
Referenced by cam.basrelief.linbcg.
cam.basrelief.atimes(x, res)
Referenced by cam.basrelief.linbcg, cam.basrelief.problemAreas.
cam.basrelief.snrm(n, sx, itol)
Referenced by cam.basrelief.linbcg.
cam.basrelief.linbcg(n, b, x, itol, tol, itmax, iter, err, rows, cols, planar)
References cam.basrelief.asolve, cam.basrelief.atimes, cam.basrelief.snrm.
Referenced by cam.basrelief.smooth.
cam.basrelief.numpysave(a, iname)
References cam.basrelief.numpytoimage.
cam.basrelief.numpytoimage(a, iname)
Referenced by cam.basrelief.numpysave, cam.basrelief.problemAreas.
cam.basrelief.imagetonumpy(i)
Referenced by cam.basrelief.problemAreas, cam.basrelief.relief.
cam.basrelief.tonemap(i, exponent)
Referenced by cam.basrelief.problemAreas, cam.basrelief.relief.
cam.basrelief.vert(column, row, z, XYscaling, Zscaling)
Create a Single Vert
Referenced by cam.basrelief.buildMesh.
cam.basrelief.buildMesh(mesh_z, br)
References cam.basrelief.vert.
Referenced by cam.basrelief.relief.
cam.basrelief.renderScene(width, height, bit_diameter, passes_per_radius, make_nodes, view_layer)
Referenced by cam.basrelief.DoBasRelief.execute.
cam.basrelief.problemAreas(br)
References cam.basrelief.atimes, cam.basrelief.imagetonumpy, cam.basrelief.numpytoimage, cam.basrelief.tonemap.
Referenced by cam.basrelief.ProblemAreas.execute.
cam.basrelief.relief(br)
References cam.basrelief.buildMesh, cam.basrelief.imagetonumpy, cam.basrelief.solve_pde_multigrid, cam.basrelief.tonemap.
Referenced by cam.basrelief.DoBasRelief.execute.
cam.basrelief.get_panels()
cam.basrelief.register()
cam.basrelief.unregister()