cam::simulation
cam.simulation.createSimulationObject(name, operations, i)
Referenced by cam.simulation.doSimulation.
cam.simulation.doSimulation(name, operations)
Perform Simulation of Operations. Currently only for 3 Axis
References cam.simulation.createSimulationObject, cam.simulation.generateSimulationImage.
cam.simulation.generateSimulationImage(operations, limits)
References cam.simulation.simCutterSpot.
Referenced by cam.simulation.doSimulation.
cam.simulation.simCutterSpot(xs, ys, z, cutterArray, si, getvolume=False)
Simulates a Cutter Cutting Into Stock, Taking Away the Volume, and Optionally Returning the Volume that Has Been Milled. This Is Now Used for Feedrate Tweaking.
Referenced by cam.simulation.generateSimulationImage.