cam::joinery
cam.joinery.finger_amount(space, size)
cam.joinery.mortise(length, thickness, finger_play, cx=0, cy=0, rotation=0)
Referenced by cam.joinery.fixed_finger, cam.joinery.horizontal_finger, cam.joinery.interlock_groove, cam.joinery.interlock_twist, cam.joinery.make_flex_pocket, cam.joinery.make_variable_flex_pocket, cam.joinery.variable_finger, cam.joinery.vertical_finger.
cam.joinery.interlock_groove(length, thickness, finger_play, cx=0, cy=0, rotation=0)
References cam.joinery.mortise.
Referenced by cam.joinery.single_interlock.
cam.joinery.interlock_twist(length, thickness, finger_play, cx=0, cy=0, rotation=0, percentage=0.5)
References cam.joinery.mortise.
Referenced by cam.joinery.single_interlock, cam.joinery.twist_line.
cam.joinery.twist_line(length, thickness, finger_play, percentage, amount, distance, center=True)
References cam.joinery.interlock_twist.
cam.joinery.twist_separator_slot(length, thickness, finger_play=0.00005, percentage=0.5)
Referenced by cam.joinery.interlock_twist_separator.
cam.joinery.interlock_twist_separator(length, thickness, amount, spacing, edge_distance, finger_play=0.00005, percentage=0.5, start='rounded', end='rounded')
References cam.joinery.twist_separator_slot.
cam.joinery.horizontal_finger(length, thickness, finger_play, amount, center=True)
References cam.joinery.mortise.
cam.joinery.vertical_finger(length, thickness, finger_play, amount)
References cam.joinery.mortise.
cam.joinery.finger_pair(name, dx=0, dy=0)
Referenced by cam.joinery.create_flex_side.
cam.joinery.create_base_plate(height, width, depth)
cam.joinery.make_flex_pocket(length, height, finger_thick, finger_width, pocket_width)
References cam.joinery.mortise.
cam.joinery.make_variable_flex_pocket(height, finger_thick, pocket_width, locations)
References cam.joinery.mortise.
cam.joinery.create_flex_side(length, height, finger_thick, top_bottom=False)
References cam.joinery.finger_pair.
cam.joinery.angle(a, b)
Referenced by cam.joinery.angle_difference, cam.joinery.distributed_interlock, cam.joinery.dslope_array, cam.joinery.fixed_finger, cam.joinery.variable_finger.
cam.joinery.angle_difference(a, b, c)
References cam.joinery.angle.
cam.joinery.fixed_finger(loop, loop_length, finger_size, finger_thick, finger_tolerance, base=False)
References cam.joinery.angle, cam.joinery.mortise.
cam.joinery.find_slope(p1, p2)
Referenced by cam.joinery.dslope_array, cam.joinery.slope_array.
cam.joinery.slope_array(loop)
References cam.joinery.find_slope.
cam.joinery.dslope_array(loop, resolution=0.001)
References cam.joinery.angle, cam.joinery.find_slope.
cam.joinery.variable_finger(loop, loop_length, min_finger, finger_size, finger_thick, finger_tolerance, adaptive, base=False, double_adaptive=False)
References cam.joinery.angle, cam.joinery.mortise.
cam.joinery.single_interlock(finger_depth, finger_thick, finger_tolerance, x, y, groove_angle, type, amount=1, twist_percentage=0.5)
References cam.joinery.interlock_groove, cam.joinery.interlock_twist.
Referenced by cam.joinery.distributed_interlock.
cam.joinery.distributed_interlock(loop, loop_length, finger_depth, finger_thick, finger_tolerance, finger_amount, tangent=0, fixed_angle=0, start=0.01, end=0.01, closed=True, type='GROOVE', twist_percentage=0.5)
References cam.joinery.angle, cam.joinery.single_interlock.