cam::testing
list cam::testing.tests
int cam::testing.p
cam.testing.addTestCurve(loc)
Referenced by cam.testing.testCutout, cam.testing.testPocket.
cam.testing.addTestMesh(loc)
Referenced by cam.testing.testParallel, cam.testing.testWaterline.
cam.testing.deleteFirstVert(ob)
Referenced by cam.testing.testCalc.
cam.testing.testCalc(o)
References cam.testing.deleteFirstVert.
Referenced by cam.testing.testCutout, cam.testing.testPocket, cam.testing.testWaterline.
cam.testing.testCutout(pos)
References cam.testing.addTestCurve, cam.testing.testCalc.
cam.testing.testPocket(pos)
References cam.testing.addTestCurve, cam.testing.testCalc.
cam.testing.testParallel(pos)
References cam.testing.addTestMesh.
cam.testing.testWaterline(pos)
References cam.testing.addTestMesh, cam.testing.testCalc.
cam.testing.testSimulation()
cam.testing.cleanUp()
cam.testing.testOperation(i)
Referenced by cam.testing.testAll.
cam.testing.testAll()
References cam.testing.testOperation.