cam::opencamlib::opencamlib
float cam::opencamlib::opencamlib.OCL_SCALE
cam::opencamlib::opencamlib.PYTHON_BIN
cam.opencamlib.opencamlib.pointSamplesFromOCL(points, samples)
Referenced by cam.opencamlib.opencamlib.oclSamplePoints.
cam.opencamlib.opencamlib.chunkPointSamplesFromOCL(chunks, samples)
Referenced by cam.opencamlib.opencamlib.oclSample.
cam.opencamlib.opencamlib.chunkPointsResampleFromOCL(chunks, samples)
cam.opencamlib.opencamlib.exportModelsToSTL(operation)
cam.opencamlib.opencamlib.oclSamplePoints(operation, points)
References cam.opencamlib.opencamlib.pointSamplesFromOCL.
cam.opencamlib.opencamlib.oclSample(operation, chunks)
References cam.opencamlib.opencamlib.chunkPointSamplesFromOCL.
cam.opencamlib.opencamlib.oclResampleChunks(operation, chunks_to_resample, use_cached_mesh)
cam.opencamlib.opencamlib.oclWaterlineLayerHeights(operation)
Referenced by cam.opencamlib.opencamlib.oclGetWaterline.
cam.opencamlib.opencamlib.oclGetWaterline(operation, chunks)
References cam.opencamlib.opencamlib.oclWaterlineLayerHeights.