cam::voronoi
int cam::voronoi.TOLERANCE
int cam::voronoi.BIG_FLOAT
bool cam::voronoi::PY3
cam.voronoi.voronoi(siteList, context)
cam.voronoi.isEqual(a, b, relativeError=TOLERANCE)
Referenced by cam.voronoi.Halfedge.intersect.
cam.voronoi.computeVoronoiDiagram(points, xBuff=0, yBuff=0, polygonsOutput=False, formatOutput=False, closePoly=True)
Takes : - a list of point objects (which must have x and y fields). - x and y buffer values which are the expansion percentages of the bounding box rectangle including all input points. Returns : - With default options : A list of 2-tuples, representing the two points of each Voronoi diagram edge. Each point contains 2-tuples which are the x,y coordinates of point. if formatOutput is True, returns : - a list of 2-tuples, which are the x,y coordinates of the Voronoi diagram vertices. - and a list of 2-tuples (v1, v2) representing edges of the Voronoi diagram. v1 and v2 are the indices of the vertices at the end of the edge. - If polygonsOutput option is True, returns : A dictionary of polygons, keys are the indices of the input points, values contains n-tuples representing the n points of each Voronoi diagram polygon. Each point contains 2-tuples which are the x,y coordinates of point. if formatOutput is True, returns : - A list of 2-tuples, which are the x,y coordinates of the Voronoi diagram vertices. - and a dictionary of input points indices. Values contains n-tuples representing the n points of each Voronoi diagram polygon. Each tuple contains the vertex indices of the polygon vertices. - if closePoly is True then, in the list of points of a polygon, last point will be the same of first point
References cam.voronoi.formatEdgesOutput, cam.voronoi.formatPolygonsOutput.
cam.voronoi.formatEdgesOutput(edges)
Referenced by cam.voronoi.computeVoronoiDiagram.
cam.voronoi.formatPolygonsOutput(polygons)
Referenced by cam.voronoi.computeVoronoiDiagram.
cam.voronoi.computeDelaunayTriangulation(points)
Takes a list of point objects (which must have x and y fields). Returns a list of 3-tuples: the indices of the points that form a Delaunay triangle.