cam::cam_chunk
cam.cam_chunk.Rotate_pbyp(originp, p, ang)
Referenced by cam.cam_chunk.camPathChunk.leadContour.
cam.cam_chunk._internalXyDistanceTo(ourpoints, theirpoints, cutoff)
Referenced by cam.cam_chunk.camPathChunk.xyDistanceTo, cam.cam_chunk.camPathChunk.xyDistanceWithin.
cam.cam_chunk.chunksCoherency(chunks)
cam.cam_chunk.setChunksZ(chunks, z)
cam.cam_chunk._optimize_internal(points, keep_points, e, protect_vertical, protect_vertical_limit)
Referenced by cam.cam_chunk.optimizeChunk.
cam.cam_chunk.optimizeChunk(chunk, operation)
References cam.cam_chunk._optimize_internal.
cam.cam_chunk.limitChunks(chunks, o, force=False)
cam.cam_chunk.parentChildPoly(parents, children, o)
cam.cam_chunk.parentChildDist(parents, children, o, distance=None)
cam.cam_chunk.parentChild(parents, children, o)
cam.cam_chunk.chunksToShapely(chunks)
cam.cam_chunk.meshFromCurveToChunk(object)
Referenced by cam.cam_chunk.curveToChunks.
cam.cam_chunk.makeVisible(o)
cam.cam_chunk.restoreVisibility(o, storage)
cam.cam_chunk.meshFromCurve(o, use_modifiers=False)
Referenced by cam.cam_chunk.curveToChunks.
cam.cam_chunk.curveToChunks(o, use_modifiers=False)
References cam.cam_chunk.meshFromCurve, cam.cam_chunk.meshFromCurveToChunk.
cam.cam_chunk.shapelyToChunks(p, zlevel)
cam.cam_chunk.chunkToShapely(chunk)
cam.cam_chunk.chunksRefine(chunks, o)
Add Extra Points in Between for Chunks
cam.cam_chunk.chunksRefineThreshold(chunks, distance, limitdistance)
Add Extra Points in Between for Chunks. for Medial Axis Strategy only!