cam::ops
cam.ops.threadread(tcom)
Reads Stdout of Background Process, Done This Way to Have It Non-blocking
cam.ops.timer_update(context)
Monitoring of Background Processes
cam.ops._calc_path(operator, context)
Referenced by cam.ops.CalculatePath.execute_async, cam.ops.PathsChain.execute_async.
cam.ops.getChainOperations(chain)
Return Chain Operations, Currently Chain Object Can't Store Operations Directly Due to Blender Limitations
Referenced by cam.ops.PathExportChain.execute, cam.ops.PathsChain.execute_async, cam.ops.CAMSimulateChain.execute_async.
cam.ops.fixUnits()
Sets up Units for BlenderCAM
Referenced by cam.ops.CamOperationAdd.execute, cam.ops.CamOperationCopy.execute.