cam::puzzle_joinery
float cam::puzzle_joinery.DT
cam.puzzle_joinery.finger(diameter, stem=2)
Referenced by cam.puzzle_joinery.fingers.
cam.puzzle_joinery.fingers(diameter, inside, amount=1, stem=1)
References cam.puzzle_joinery.finger.
Referenced by cam.puzzle_joinery.arc, cam.puzzle_joinery.bar, cam.puzzle_joinery.mitre, cam.puzzle_joinery.open_curve, cam.puzzle_joinery.t, cam.puzzle_joinery.tile.
cam.puzzle_joinery.twistf(name, length, diameter, tolerance, twist, tneck, tthick, twist_keep=False)
Referenced by cam.puzzle_joinery.arc, cam.puzzle_joinery.bar, cam.puzzle_joinery.open_curve.
cam.puzzle_joinery.twistm(name, length, diameter, tolerance, twist, tneck, tthick, angle, twist_keep=False, x=0, y=0)
Referenced by cam.puzzle_joinery.arc, cam.puzzle_joinery.bar, cam.puzzle_joinery.open_curve.
cam.puzzle_joinery.bar(width, thick, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, twist_keep=False, twist_line=False, twist_line_amount=2, which='MF')
References cam.puzzle_joinery.fingers, cam.puzzle_joinery.twistf, cam.puzzle_joinery.twistm.
Referenced by cam.puzzle_joinery.arcbar, cam.puzzle_joinery.curved_t, cam.puzzle_joinery.t.
cam.puzzle_joinery.arc(radius, thick, angle, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, twist_keep=False, which='MF')
References cam.puzzle_joinery.fingers, cam.puzzle_joinery.twistf, cam.puzzle_joinery.twistm.
Referenced by cam.puzzle_joinery.arcbar, cam.puzzle_joinery.arcbararc, cam.puzzle_joinery.curved_t, cam.puzzle_joinery.multiangle.
cam.puzzle_joinery.arcbararc(length, radius, thick, angle, angleb, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, which='MF', twist_keep=False, twist_line=False, twist_line_amount=2)
References cam.puzzle_joinery.arc.
cam.puzzle_joinery.arcbar(length, radius, thick, angle, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, twist_keep=False, which='MF', twist_line=False, twist_line_amount=2)
References cam.puzzle_joinery.arc, cam.puzzle_joinery.bar.
cam.puzzle_joinery.multiangle(radius, thick, angle, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, combination='MFF')
References cam.puzzle_joinery.arc.
cam.puzzle_joinery.t(length, thick, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, combination='MF', base_gender='M', corner=False)
References cam.puzzle_joinery.bar, cam.puzzle_joinery.fingers.
cam.puzzle_joinery.curved_t(length, thick, radius, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, combination='MF', base_gender='M')
References cam.puzzle_joinery.arc, cam.puzzle_joinery.bar.
cam.puzzle_joinery.mitre(length, thick, angle, angleb, diameter, tolerance, amount=0, stem=1, twist=False, tneck=0.5, tthick=0.01, which='MF')
References cam.puzzle_joinery.fingers.
cam.puzzle_joinery.open_curve(line, thick, diameter, tolerance, amount=0, stem=1, twist=False, t_neck=0.5, t_thick=0.01, twist_amount=1, which='MF', twist_keep=False)
References cam.puzzle_joinery.fingers, cam.puzzle_joinery.twistf, cam.puzzle_joinery.twistm.
cam.puzzle_joinery.tile(diameter, tolerance, tile_x_amount, tile_y_amount, stem=1)
References cam.puzzle_joinery.fingers.