cam::image_utils
cam.image_utils.numpysave(a, iname)
References cam.image_utils.numpytoimage.
cam.image_utils.getCircle(r, z)
cam.image_utils.getCircleBinary(r)
Referenced by cam.image_utils.crazyStrokeImage, cam.image_utils.crazyStrokeImageBinary.
cam.image_utils.numpytoimage(a, iname)
Referenced by cam.image_utils.numpysave.
cam.image_utils.imagetonumpy(i)
Referenced by cam.image_utils.prepareArea, cam.image_utils.renderSampleImage.
cam.image_utils._offset_inner_loop(y1, y2, cutterArrayNan, cwidth, sourceArray, width, height, comparearea)
Referenced by cam.image_utils.offsetArea.
cam.image_utils.offsetArea(o, samples)
Offsets the Whole Image with the Cutter + Skin Offsets
References cam.image_utils._offset_inner_loop.
Referenced by cam.image_utils.prepareArea.
cam.image_utils.dilateAr(ar, cycles)
cam.image_utils.getOffsetImageCavities(o, i)
Detects Areas in the Offset Image Which Are 'cavities' - the Curvature Changes.
References cam.image_utils.imageEdgeSearch_online.
cam.image_utils.imageEdgeSearch_online(o, ar, zimage)
Referenced by cam.image_utils.getOffsetImageCavities.
cam.image_utils.crazyPath(o)
cam.image_utils.buildStroke(start, end, cutterArray)
cam.image_utils.testStroke()
cam.image_utils.applyStroke()
cam.image_utils.testStrokeBinary(img, stroke)
cam.image_utils.crazyStrokeImage(o)
References cam.image_utils.getCircleBinary.
cam.image_utils.crazyStrokeImageBinary(o, ar, avoidar)
References cam.image_utils.getCircleBinary.
cam.image_utils.imageToChunks(o, image, with_border=False)
cam.image_utils.imageToShapely(o, i, with_border=False)
cam.image_utils.getSampleImage(s, sarray, minz)
cam.image_utils.getResolution(o)
cam.image_utils._backup_render_settings(pairs)
Referenced by cam.image_utils.renderSampleImage.
cam.image_utils._restore_render_settings(pairs, properties)
Referenced by cam.image_utils.renderSampleImage.
cam.image_utils.renderSampleImage(o)
References cam.image_utils._backup_render_settings, cam.image_utils._restore_render_settings, cam.image_utils.imagetonumpy.
cam.image_utils.prepareArea(o)
References cam.image_utils.imagetonumpy, cam.image_utils.offsetArea.
cam.image_utils.getCutterArray(operation, pixsize)